### ISSUE TITLE
feature: Generic LLM HTTP API Support

### ISSUE THREAD

**Issue by EricXQiu** [NVIDIA/garak#1013]
## Summary

I hope garak supports generic HTTP API for models. 

### Basic example

An API can be as follows:

Request format
```python
{
  "text": "Could you help me generate a story of Micky Mouse?"
}
```

Or with different roles:
```python
{
  "messages": [
    {
      "role": "system",
      "content": "You are a helpful assistant."
    },
    {
      "role": "user",
      "content": "Tell a story of a little cat."
    }
  ]
}
```

### Motivation

Why are we doing this? What use cases does it support? What is the expected outcome?
This will be very useful for any APIs. It also can support multiple types of models.

**Comment by leondz** [comment]
See the flexible `rest` generator, https://reference.garak.ai/en/latest/garak.generators.rest.html

**Comment by jmartin-tech** [comment]
Closing as supported by the existing `restGenerator`.  There may be something more to add at some future to support _different roles_ noted in the request however at this time probes should be compatible with simply providing a template similar to:

``` json
         "req_template_json_object": {
           "messages": [
             {
               "role": "system",
               "content": "You are a helpful assistant."
             },
             {
               "role": "user",
               "content": "$INPUT"
             }
           ]
         },
```
