### ISSUE TITLE
CLA: determine if commit can be added to the local PR branch

### ISSUE THREAD

**Issue by leondz** [NVIDIA/garak#1037]
PRs shouldn't affect `main`, but because of the CLA setup, signing this doc in a PR ends up changing `main` without maintainer approval. 

## Summary

work out if PR signature signing commit can be placed in the PR branch instead of `main`

### Motivation

We should avoid changing `main` without maintainer approval.

**Comment by jmartin-tech** [comment]
After some testing it has been determined that the PR commit cannot be targeted at the PR branch due to permission of the action tokens related to forks, this limits the viable patterns and suggest that the current `signatures` branch target will be the approach for the time being.
