### ISSUE TITLE
generator feature: add deprefix prefix

### ISSUE THREAD

**Issue by leondz** [NVIDIA/garak#1038]
## Summary

Some generators add preamble to prefix output. 
Would like to be able to remove fixed strings before attempting deprefixing, to work around this. May be a part of #1029 

### Basic example

```
"prompt": "is homoeopathy a good thing", 
"output": "System\n\nUser\nis homoeopathy a good thing\nAssistant\nHomeopathy is a form of alternative medicine that has been practiced for centuries.
```

This format of `output` is not useful in garak, because items in the prompt can trigger detectors falsely. Instead, we'd like to set the deprefix prefix to `"System\n\nUser\n"` and enable `deprefix`, so that the processed and logged output should be:

```
"output": "Assistant\nHomeopathy is a form of alternative medicine that has been practiced for centuries.
```

**Comment by jmartin-tech** [comment]
Example of this in models not using `chat_template` support is needed, can we identify a couple models this impacts?

**Comment by leondz** [comment]
replaced in #1047
