### ISSUE TITLE
tap.PAIR getting "run_tap() got an unexpected keyword argument 'evaluator_model'"

### ISSUE THREAD

**Issue by rafaelsandroni** [NVIDIA/garak#1044]
## Steps to reproduce

$ python3 -m garak --model_type openai --model_name gpt-4 --probes tap.PAIR

```
🕵️  queue of probes: tap.PAIR
PAIR generation encountered an error:
run_tap() got an unexpected keyword argument 'evaluator_model'

```

## Current behavior

Getting error: run_tap() got an unexpected keyword argument 'evaluator_model'

### garak version

v0.10.0.post1

## Additional Information

2. Python version: 3.11
3. Install method (`pip` based repo install)

**Comment by jmartin-tech** [comment]
Fixed via #1045
